[Debug]
; Adds more logging during file parsing and logs subtitles (INFO NAM1)
bEnableDebugLog = false
; Adds the FormID and plugin as a prefix to all replacement strings in the game.
; This is useful, for example, if you want to check whether a string has been modified by DSD.
bEnableDebugInfo = false
; Update interval of the conditions. Lower: more updates, higher workload; Higher: fewer updates, lower workload
; Interval is in seconds, but will scale with the game time scale
; 0.0 or negative means no updates
fUpdateInterval = 5.0