[Debug]
; Adds more logging during file parsing and logs subtitles (INFO NAM1)
EnableDebugLog = false
; Adds the FormID and plugin as a prefix to all replacement strings in the game.
; This is useful, for example, if you want to check whether a string has been modified by DSD.
EnableDebugInfo = false